# Stage 1: Build React app
FROM node:21-alpine3.19 as builder

# Update and install yarn
RUN apk update && apk add --no-cache npm

# Set the working directory
WORKDIR /frontend

# Copy the rest of the application source code
COPY . .

# Install dependencies
RUN npm install -g npm@11.3.0
RUN npm install --force

# Build the React app
RUN NODE_OPTIONS=--max_old_space_size=4096 npm run build

# Stage 2: Serve the React app using Nginx
FROM nginx:1.23.1-alpine

# Copy the built React app from the builder stage
COPY --from=builder /frontend/build /usr/share/nginx/html

# Copy the Nginx config file from the builder stage
COPY --from=builder /frontend/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /frontend /frontend

# Expose the port Nginx is running on
EXPOSE 80

# Command to run Nginx
CMD ["nginx", "-g", "daemon off;"]