# Stage 1: Build React app
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /frontend

# Install dependencies
COPY package*.json ./
RUN npm install --force

# Copy app source
COPY . .

# Build app
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:1.23.1-alpine

# Copy build output to Nginx html folder
COPY --from=builder /frontend/dist /usr/share/nginx/html

# Copy custom Nginx config
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
